global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'jenkins'
    static_configs:
      - targets: ['jenkins:8080']

  - job_name: 'spring-boot-app'
    static_configs:
      - targets: ['backend:8089']
