global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'jenkins'
    metrics_path: /prometheus
    static_configs:
      - targets: ['192.168.33.10:8080']

  - job_name: 'spring-boot-app'
    static_configs:
      - targets: ['192.168.33.10:8089']
